[18:48, 04/04/2026] +221 78 308 86 47: 🚨🚨chambre douche a partagé accès à la cuisine et au salon au rez-de-chaussée a derkle non loins de la maman congolaise qui vend les beignets 

62500×3

Déjà libre pour une fille étrangère 

Vidéo inbox 

Tel 78 308 86 47
[18:48, 04/04/2026] +221 78 308 86 47: 🚨🚨Grande Mosquée Niarry Tally 

👉🏽Grande Chambre 🛌 + Balcon 🪑 + accès à la cuisine 🍽️ + Douche partagée 

💢 Prix : 65000/mois

🗝️ Conditions 03mois
Disponible déjà

Vidéo inbox 

Tel 78 308 86 47
[18:48, 04/04/2026] +221 78 308 86 47: 🚨🚨Chambre douche à côté personnelle accès cuisine et salon à louer aux Mamelles vers le monument

80.000×3

Fille de préférence 

Disponible 01 Avril,possibilité de visiter

Tel 78 308 86 47
[18:49, 04/04/2026] +221 78 308 86 47: 🚨🚨Une grande chambre balcon douche à partager avec une personne accès cuisine à louer à Ouest foire vers la Station Shell

85.000×3

Déjà disponible 

Vidéo inbox 

Tel 78 308 86 47
[18:49, 04/04/2026] +221 78 308 86 47: 🚨🚨chambre douche interne accès cuisine a dieupeul non loin de l'université bourguiba 

89.000×2 ( loyer et commission)

Pas de caution 

Visite seulement 

NB garçon étrangers seulement 

Tel 78 308 86 47
[18:49, 04/04/2026] +221 78 308 86 47: 🚨🚨Un grand salon + balcon
Douche extérieure accès à la cuisine déjà disponible marché samedi à 75.000

Déjà libre Possible de visiter et de finaliser 

 vidéo inbox 

Tel 78 308 86 47
[18:49, 04/04/2026] +221 78 308 86 47: 🚨🚨Mini studio à Fass vers le canal 4 au 1iere étage 
Chambre douche cuisine ( américaine)

100.000×3

Pas des images visite seulement 

Tel 78 308 86 47
[18:56, 04/04/2026] Momo & Co.: Chambre disponible dès demain – Grand Dakar, Rue GD 34

Chambre à louer dans un studio, idéalement située à Grand Dakar, à proximité du centre de santé.

💰 Conditions : 65 000 FCFA x 3
(accès, caution et mois en cours)

📍 Quartier accessible et pratique (transport, commerces, services)

📅 Disponible immédiatement
[19:01, 04/04/2026] +221 77 668 15 32: Saraaakh 12pro max 256gb turbo letsgo déjà actif ecran changer bêta réparation 73% lo fayy? Ma diayla!!😩
[19:01, 04/04/2026] +221 78 179 77 51: Chère Communauté, je vous invite à prendre connaissance des 4 Piliers de notre Projet :  Le PACTE SOCIAL

#ACT 2

Pour accéder à la vidéo complète 👇👇👇:
https://www.facebook.com/share/v/17A9Q5AVsb/

https://vt.tiktok.com/ZSHraCKKe/

#Tous Acteurs du Pacte Social🚂✈️
[19:03, 04/04/2026] +221 77 553 46 37: 🏠 Mini studio à louer – Ouakam (vers Mon Prix)

✔️ Chambre
✔️ Toilette
✔️ Cuisine
✔️ Rez-de-chaussée
✔️ Déjà disponible
🌍 Étrangers acceptés

💰 Loyer : 125 000 FCFA / mois
[19:06, 04/04/2026] +221 78 482 59 74: 🟢Salam la famille !
* Studio chambre salon transformable 2 douches 
210.000
Sacré cœur 3 

* studio chambre salon transformable avec balcon 
2 douches 
Ouest foire 
200.000

* Deux appartements dans le même immeuble.
2 chambres salon transformable deux douches 
300.000
Liberté 6 extension 
1er 

2 chambres salon transformable 2 douches 
300.000
Liberté 6 extension 
Rez-de-chaussée 

* Chambre indépendante avec salle de bain accès cuisine 
85.000
Sacré cœur 3
Prend étranger (désolé c’est la condition du logeur) 
Tel:78 482 59 74